const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType
} = require("docx");

const OUTPUT_DIR = path.join(__dirname, "..", "generated");

function ensureOutputDir() {
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }
}

function safeFileName(name) {
    return String(name || "mechsyntra-assignment")
        .replace(/[^a-z0-9-_]+/gi, "_")
        .replace(/^_+|_+$/g, "")
        .slice(0, 80) || "mechsyntra-assignment";
}

function splitContent(content) {
    return String(content || "")
        .replace(/\r/g, "")
        .split("\n")
        .map(line => line.trim())
        .filter(Boolean);
}

async function createWordDocument({
    title,
    content,
    fileName
}) {
    ensureOutputDir();

    const children = [];

    children.push(
        new Paragraph({
            text: title || "Assignment",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER
        })
    );

    children.push(
        new Paragraph({
            text: "Generated by MechSyntra AI",
            alignment: AlignmentType.CENTER
        })
    );

    children.push(
        new Paragraph({
            text: ""
        })
    );

    const lines = splitContent(content);

    for (const line of lines) {
        const isHeading =
            line.length < 100 &&
            (
                /^(\d+[\.\)]|chapter|introduction|conclusion|references|abstract|summary|objectives|methodology|discussion|results)\b/i.test(line)
            );

        if (isHeading) {
            children.push(
                new Paragraph({
                    text: line,
                    heading: HeadingLevel.HEADING_2
                })
            );
        } else {
            children.push(
                new Paragraph({
                    children: [
                        new TextRun({
                            text: line
                        })
                    ],
                    spacing: {
                        after: 180
                    }
                })
            );
        }
    }

    const document = new Document({
        sections: [
            {
                properties: {},
                children
            }
        ]
    });

    const buffer = await Packer.toBuffer(document);

    const outputName =
        `${safeFileName(fileName || title)}.docx`;

    const outputPath =
        path.join(OUTPUT_DIR, outputName);

    fs.writeFileSync(
        outputPath,
        buffer
    );

    return {
        fileName: outputName,
        filePath: outputPath,
        mimeType:
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    };
}

async function createPdfDocument({
    title,
    content,
    fileName
}) {
    ensureOutputDir();

    const outputName =
        `${safeFileName(fileName || title)}.pdf`;

    const outputPath =
        path.join(OUTPUT_DIR, outputName);

    return new Promise((resolve, reject) => {
        const pdf =
            new PDFDocument({
                margin: 60,
                size: "A4"
            });

        const stream =
            fs.createWriteStream(
                outputPath
            );

        stream.on(
            "finish",
            () => {
                resolve({
                    fileName: outputName,
                    filePath: outputPath,
                    mimeType:
                        "application/pdf"
                });
            }
        );

        stream.on(
            "error",
            reject
        );

        pdf.pipe(stream);

        pdf.fontSize(22)
            .font("Helvetica-Bold")
            .text(
                title || "Assignment",
                {
                    align: "center"
                }
            );

        pdf.moveDown(0.5);

        pdf.fontSize(10)
            .font("Helvetica")
            .text(
                "Generated by MechSyntra AI",
                {
                    align: "center"
                }
            );

        pdf.moveDown(2);

        const lines =
            splitContent(content);

        for (const line of lines) {
            const isHeading =
                line.length < 100 &&
                (
                    /^(\d+[\.\)]|chapter|introduction|conclusion|references|abstract|summary|objectives|methodology|discussion|results)\b/i.test(line)
                );

            if (isHeading) {
                pdf.moveDown(0.7);

                pdf.fontSize(14)
                    .font("Helvetica-Bold")
                    .text(line);

                pdf.moveDown(0.2);
            } else {
                pdf.fontSize(11)
                    .font("Helvetica")
                    .text(line, {
                        align: "left",
                        lineGap: 4
                    });

                pdf.moveDown(0.5);
            }
        }

        pdf.end();
    });
}

module.exports = {
    createWordDocument,
    createPdfDocument
};